version: '3.9'

services:
  midiot.api:
    image: ${DOCKER_REGISTRY-}midiot.api
    container_name: midiot.api
    environment:
        ConnectionStrings__DefaultConnection: "${Db_Connect}"
        JwtOptions__Issuer: Midiot.API
        JwtOptions__SecretKey: "${JwtOptions__SecretKey}"
        SendGridOptions__ApiKey: "${SendGridOptions__ApiKey}"
        SendGridOptions__FromEmail: "${SendGridOptions__FromEmail}"
    build:
      context: .
      dockerfile: ./Midiot.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       - midiot.postgres

  midiot.postgres:
    image: postgres:latest
    container_name: midiot.postgres
    environment:
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
     - pgdata:/var/lib/postgresql/data
    ports:
     - 5433:5432

  midiot.pgadmin:
    container_name: midiot.pgadmin
    image: 'docker.io/dpage/pgadmin4:latest'
    environment:
        PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
        PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
    pgdata:
    pgadmin-data:
